### ISSUE TITLE
Error after few iteration on training

### ISSUE THREAD

**Issue by yaju1234** [Karel911/TRACER#34]
I want to train the network   --arch 7 with my custom 62k dataset that is similar to DUTS. I am using 48GB CUDA and batch size 8. After a few iteration, I am getting the following error 
Traceback (most recent call last):
  File "main.py", line 55, in <module>
    main(args)
  File "main.py", line 35, in main
    Trainer(args, save_path)
  File "/root/TRACER/trainer.py", line 58, in __init__
    train_loss, train_mae = self.training(args)
  File "/root/TRACER/trainer.py", line 117, in training
    loss.backward()
  File "/root/TRACER/venv/lib/python3.6/site-packages/torch/_tensor.py", line 307, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/root/TRACER/venv/lib/python3.6/site-packages/torch/autograd/__init__.py", line 156, in backward
    allow_unreachable=True, accumulate_grad=True)  # allow_unreachable flag
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
![Screenshot from 2023-02-17 06-17-54](https://user-images.githubusercontent.com/1842237/219521671-f06db3fb-533d-47f6-9dde-03345d4a17ae.png)

**Comment by Karel911** [comment]
Please change the num of batch sizes or num_workers.
It is mainly originated from CUDA, not the codes.

**Comment by yaju1234** [comment]
I have changed the batch sizes or num_workers both but get the same error. I am using Quadro RTX 8000  48GB.

**Comment by Karel911** [comment]
Did you use a single gpu? If yes, change `multi_gpu=False` in [config](https://github.com/Karel911/TRACER/blob/main/config.py#L37).
Then, try num_workers=0. When we tried it with the same device, we could not reproduce the error.

**Comment by yaju1234** [comment]
Now I am getting the following error
Traceback (most recent call last):
  File "main.py", line 55, in <module>
    main(args)
  File "main.py", line 35, in main
    Trainer(args, save_path)
  File "/home/user/PycharmProjects/TRACER/trainer.py", line 56, in __init__
    train_loss, train_mae = self.training(args)
  File "/home/user/PycharmProjects/TRACER/trainer.py", line 106, in training
    loss1 = self.criterion(outputs, masks)
  File "/home/user/PycharmProjects/TRACER/util/losses.py", line 41, in adaptive_pixel_intensity_loss
    bce = F.binary_cross_entropy(pred, mask, reduce=None)
  File "/home/user/PycharmProjects/TRACER/venv/lib/python3.6/site-packages/torch/nn/functional.py", line 2915, in binary_cross_entropy
    return torch._C._nn.binary_cross_entropy(input, target, weight, reduction_enum)
RuntimeError: all elements of input should be between 0 and 1
![Screenshot from 2023-02-21 22-49-32](https://user-images.githubusercontent.com/1842237/220415707-759a512d-495e-4920-8902-1e1ba205d75b.png)

**Comment by Karel911** [comment]
It seems there are negative or nan values in your output or labels.
Please check the values.
